### ISSUE TITLE
Limitation of scope

### ISSUE THREAD

**Issue by mrmlnc** [formulahendry/vscode-auto-close-tag#1]
![2016-06-28_20-42-22](https://cloud.githubusercontent.com/assets/7034281/16426282/04bcc164-3d71-11e6-8486-6812839a359d.gif)

**Comment by formulahendry** [comment]
Hi mrmlnc,
I have added a setting entry to set the languages that the extension will be activated. 
You could install the latest version and add settings like below in the File->Preferences->User Settings for whatever language you want to use this extension.
```json
{
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php"
    ]
}
```

**Comment by mrmlnc** [comment]
Thanks :+1:
