### ISSUE TITLE
Auto close not working in VSCode 1.27.2.

### ISSUE THREAD

**Issue by cberry216** [formulahendry/vscode-auto-close-tag#102]
Using Auto Close Tag v.0.5.6 and whenever I close the first tag (e.g. <html>) the auto closing tag doesn't show up.

**Comment by cberry216** [comment]
The problem was, the html file was a Django HTML file and not a plain HTML. Changing the file type from Django HTML to HTML fixed it.

**Comment by nrghisoka** [comment]
Incase anyone else comes across this, you can also add the 'django-html' file type to vs code settings.json file.
Add to settings:
"auto-close-tag.activationOnLanguage": [
    'django-html'
]

**Comment by famdude** [comment]
> 

It saved me :)
I had added 'django' and it wasn't working! By reading your solution, I figured out the problem.

**Comment by famdude** [comment]
> Incase anyone else comes across this, you can also add the 'django-html' file type to vs code settings.json file. Add to settings: "auto-close-tag.activationOnLanguage": [ 'django-html' ]

It saved me :)
I had added 'django' and it wasn't working! By reading your solution, I figured out the problem.
