### ISSUE TITLE
Path symbol "/" problem

### ISSUE THREAD

**Issue by u3u** [formulahendry/vscode-auto-close-tag#12]
Hi, @formulahendry
When using extension found the following questions, hope can be solved

Introducing file input path "/" symbol, automatically add ">" symbol, become "/>"
Don't want to expand in the `src` or `href` attribute within the string

**Comment by formulahendry** [comment]
Thanks @u3u for reporting it. I will investigate and find a way to fix it. For workaround before it is fixed, you could temporarily change the setting to not close self-closing tag automatically:
```json
{
    "auto-close-tag.enableAutoCloseSelfClosingTag": false
}
```

**Comment by formulahendry** [comment]
@u3u , this issue has been fixed. Please install the latest version and have a try.

**Comment by u3u** [comment]
thx
