### ISSUE TITLE
tags with . (dot) are ignored

### ISSUE THREAD

**Issue by maartencoels** [formulahendry/vscode-auto-close-tag#18]
If you have a tag with a . it will not be closed automatically.

eg:

```
<abc>
  <test.ab> x
</abc>
```

if you try to insert a tag at insertion point x it will insert `</abc>` instead of `</test.ab>`

**Comment by formulahendry** [comment]
Hi @maartencoels , this issue has been fixed, please try the latest version.

**Comment by maartencoels** [comment]
Awesome,... It works perfectly now!

Thanks !
