### ISSUE TITLE
Tag should not be auto closed inside quotes

### ISSUE THREAD

**Issue by paradox37** [formulahendry/vscode-auto-close-tag#23]
In angular 2, I often use condition like this:

`<div *ngIf ="variable>0"><div>`

Upon pressing > plugin will attempt to auto close the div tag inside the quotes, single or double.

This should not happen.

**Comment by formulahendry** [comment]
Hi @paradox37 , this issue has been fixed. Please try the latest version.

**Comment by paradox37** [comment]
Tested the update, works great. Thanks for the quick fix!
