### ISSUE TITLE
Extension is auto-closing generic type parameters in TypeScript

### ISSUE THREAD

**Issue by ChuckkNorris** [formulahendry/vscode-auto-close-tag#24]
When using type parameters or generics, this extension will add another closing "tag" even though it's not HTML at all.

e.g.
```
myMethod<T>() { } // When typing, <T></T> is added

doStuff() {
   myMethod<Person>(); // When typing, it adds </Person>
   myMethod<any>(); // When typing, an ending </any> tag is added
}
```

Now I could add every single type/class name to the `"auto-close-tag.excludedTags"` list, but that would be quite cumbersome.

Ideally, there would be a way to disable this extension for all `*.ts` file types. Is there a better way to prevent auto-close in my TypeScript code?

**Comment by formulahendry** [comment]
Hi @ChuckkNorris , you could set the languages that the auto-close-tag will be activated,
In VS Code, File->Preferences->User Settings, to open the settings.json. Then add config like below:
``` json
{
    "auto-close-tag.activationOnLanguage": [
        "javascript",
        "javascriptreact",
        "html",
        "xml",
        "php"
    ]
}
```
Refer to [this](https://code.visualstudio.com/docs/languages/identifiers) for the full list of Language Identifiers. 
Let me know if this works for you.

**Comment by ChuckkNorris** [comment]
Exactly what I was looking for - thanks for the help.
I'll read the docs more carefully next time.

**Comment by lucascyrne** [comment]
So if I want auto-close-tag on jsx DOM tags but at the same time, deactivate it when closing generic typescript types. simply can't I? @formulahendry 

thanks in advance.

**Comment by kellyrmilligan** [comment]
what @lucascyrne brings up is exactly how I landed here from google.

**Comment by lbfalvy** [comment]
All I want for Christmas is a setting to enable this for `.tsx` files but not for `.ts` files

**Comment by rezoled** [comment]
The issue is not closed. When writing angular code I want to get auto close in templates, but not in the typescript block of the same file.

**Comment by tincho** [comment]
when file type is "typescriptreact" 

the extension could only activate autoclosing if inside a `return` statement 

of course it's not a perfect fix, since JSX may be in a variable or non-`return` statement 

... but it would be good enough !

**Comment by fcFn** [comment]
Should be reopened so that users understand that is not solved without reading the whole thread. Thank you!

**Comment by Amixx** [comment]
Also still facing this issue!
