### ISSUE TITLE
Enable Auto Close Tag only on a set of languages

### ISSUE THREAD

**Issue by formulahendry** [formulahendry/vscode-auto-close-tag#26]
Currently, the Auto Close Tag is enabled for all languages by default. It will make more sense to only enable it on certain languages. 
The plan is as below:
```json
"auto-close-tag.activationOnLanguage": [
    "html",
    "xml",
    "php",
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "plaintext",
    "markdown",
    "razor",
    "vue"
]
```

**Comment by huyinjie** [comment]
Thanks，I think you would close this issue :)

**Comment by cgatian** [comment]
@formulahendry Any plans to do this in a release?

**Comment by formulahendry** [comment]
@cgatian Will release it. Stay tuned.

**Comment by formulahendry** [comment]
@cgatian This has been released. Please install the latest version and have a try.

**Comment by backbone87** [comment]
typescript should not be in the default, since it causes trouble with type assertions and generics.
the case for typescript with jsx (typescriptreact?) is more complicated, because the closing behavior depends on the AST

**Comment by formulahendry** [comment]
@backbone87 Augular using TypeScript also has the [embedded html](https://angular.io/docs/ts/latest/quickstart.html), so it is similar to the TypeScript with JSX. Since we are changing `["*"]` to a set of languages, I do not want remove too much languages at the early stage.
