### ISSUE TITLE
Parameter List of generic types is not a tag. 

### ISSUE THREAD

**Issue by paritosh149** [formulahendry/vscode-auto-close-tag#29]
Actual:
While writing code in Typescript, I entered following
"getData(): Promise<MyData>" 
and it converted to
"getData(): Promise<MyData></MyData>"

 Expected:
Since it is not HTML or XML tag, it should not be converted.

**Comment by formulahendry** [comment]
Hi @paritosh149  , you could set the languages that the auto-close-tag will be activated,
In VS Code, `File`->`Preferences`->`Settings`, to open the settings.json. Then add config like below:
``` json
{
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php"
    ]
}
```
Refer to [this](https://code.visualstudio.com/docs/languages/identifiers) for the full list of Language Identifiers. 
Let me know if this works for you.

**Comment by paritosh149** [comment]
No, it does not help. I am new to Angular2 and hence was working on "tours of heroes" tutorial. It contains Typescipt file that contains both HTML tags in template property and Generic classes such as Promise<>. Deactivating the auto-close-tag feature on typescript will affect the HTML tag completion in tempate property, too.

**Comment by formulahendry** [comment]
In this case, I suggest you use [Sublime Text 3 Mode](https://github.com/formulahendry/vscode-auto-close-tag#sublime-text-3-mode).
```json
{
    "auto-close-tag.SublimeText3Mode": true
}
```
Or, disable [auto-close-tag.enableAutoCloseTag](https://github.com/formulahendry/vscode-auto-close-tag#configuration) and use `Alt+.` to close tag manually.
```json
{
    "auto-close-tag.enableAutoCloseTag": false
}
```

**Comment by paritosh149** [comment]
That works for me. Thanks.
