### ISSUE TITLE
[js] Extension don't work properly when specify "js" in settings.json

### ISSUE THREAD

**Issue by OshotOkill** [formulahendry/vscode-auto-close-tag#3]
I 've been writing React code and intend to implement auto-close-tag in .js files like:
```
const App = ({children}) => <div>{children}</div>
```

At first I specified some suffixes such as `html`, `js` in `settings.json` and extension was broken, while switching back to the default `*` it worked again. I'm sure vscode was reloaded so I assume this would be the issue of extension itself.

**Comment by formulahendry** [comment]
Hi @OshotOkill , thanks for the feedback and sorry for the confusion for the definition of settings.json for this extension. The setting should be set with language id defined in VS Code not the file extension name. Per definition from [VS Code](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/package.json), we need to use `javascript` for `.js` and `.es6`, use `javascriptreact` for `.jsx`. So, if you want to enable this extension on `.js` file, you need to add `javascript` in settings.json.

**Comment by OshotOkill** [comment]
Ah I got that, it's work by now. Thanks!

**Comment by formulahendry** [comment]
Great! :smile:

**Comment by jrnail23** [comment]
"add `javascript` in settings.json" doesn't mean much to me, as I'm new to those settings.  Can I just have teh codez? 😛 
In all seriousness, though, I'd really like to see a step-by-step example of exactly how to enable auto-close for JSX in .js files.
BTW, thanks for creating this plugin!

**Comment by formulahendry** [comment]
In VS Code, File->Preferences->User Settings, to open the settings.json. Then add config like below:
```json
{
    "auto-close-tag.activationOnLanguage": [
        "javascript",
        "javascriptreact"
    ]
}
```
