### ISSUE TITLE
JSX template literal tag closing issue

### ISSUE THREAD

**Issue by hhlevnjak** [formulahendry/vscode-auto-close-tag#30]
When there is a template literal inside JSX, and you type / inside it, it automatically gets replaced with /> as if it was closing a tag.

It doesn't do that inside single or double quotes, only inside template literals.

**Comment by formulahendry** [comment]
Hi @hhlevnjak , could you share the code snippet?

**Comment by hhlevnjak** [comment]
Sure, for something like:

`<a href={`/path/${id}`}`

When you add in the slash, it looks something like:

`<a href={`/>path/${id}`}`

**Comment by formulahendry** [comment]
Thanks for reporting it! Will fix it.

**Comment by formulahendry** [comment]
Hi @hhlevnjak , this issue has been fixed. Please try the latest version.

**Comment by hhlevnjak** [comment]
Wow, this has to be the fastest fix ever. :)
