### ISSUE TITLE
After closing a tage, hitting enter doesn't do what it should.

### ISSUE THREAD

**Issue by DanJ210** [formulahendry/vscode-auto-close-tag#32]
After closing a tag your cursor sits in between the tags you just created. But, like in Visual Studio IDE, hitting enter does not go to a new line and format the tags properly... Hitting enter is as if you are accepting the second tag and goes all the way to the end of the line. One has to navigate back between the two tags and then hit enter which then does work.

Would really like for this to be changed to do exactly what the Visual Studio IDE does or this messes me up completely. It does say that this is done the same as VS IDE but that's not entirely accurate. Hopefully what I'm asking is possible or I couldn't use VSCode, it would slow me down too much.

Thanks for all the work so far! Really nice.

**Comment by fpoumian** [comment]
I'm not sure if this is the same issue than I'm having, but in JSX files the "press Enter" behavior doesn't work the same as in plain HTML files. For example, if I press Enter with the cursor between a "<p></p>" tag, then the cursor ends up at the beginning of the closing tag line, which is really annoying. In contrast, when I press Enter on a plain HTML file, then it creates a new line between the opening and closing tags, and puts the cursor in this new line.

**Comment by formulahendry** [comment]
Hi @DanJ210 , I guess your issue is the same as @fpoumian 's. But I need to say this function is not in the scope of Auto Close Tag. 
This indent function is provided by VS Code itself and it seems like it only works on HTML files but not embedded HTML in other files like JSX. You may try associate your files with HTML like below:
```json
    "files.associations": {
        "*.php": "html"
    }
```
refer to https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language

But I remember VS Code has plan to support embedded HTML. Not sure this is bug or a feature not supported yet. You may want to open an issue to VS Code repo.

**Comment by DanJ210** [comment]
@fpoumian @formulahendry I'm not sure if we are all talking about the same thing here.

If you going into the regular Visual Studio IDE and edit an HTML file. You open a tag like <html>, when type that last ">" then the closing tag automatically adds itself, you can then hit enter which formats it, splitting up the tags on different lines while putting you cursor in the center with an indent. If you do this in visual studio code it doesn't do this, when you hit enter it goes to the end of the closing tag... No formatting at all. Is this what we are talking about here?

Just to be clear, I'm not talking about any other editing except in HTML files only. Though the above setting does give me helpful knowledge and I do appreaciate that @formulahendry .

**Comment by formulahendry** [comment]
@DanJ210 Are you talking about the format (i.e. indent) as below? And the indent only works in HTML files?
![indent](https://cloud.githubusercontent.com/assets/1050213/24087460/4ec17caa-0d5a-11e7-88d1-9f28c6e6ba9a.gif)
If yes, you may want to open an issue to VS Code repo. 😄

**Comment by Madebym** [comment]
Just to chime in on this, cause I think I have the same problem.

If I auto-close empty paragraph or div, then press enter, I get the desired behaviour. That would be the exact bahaviour as on the GIF above.

If I add a class or ID to the div or paragraph, then pressing enter leads me to the end of that line, like I pressed TAB.

Honestly, I don't get why it behaves like that? I just switched from Brackets(tried Atom also), and this auto-close stuff works as it should.

**Comment by DanJ210** [comment]
@formulahendry Yes I'm talking about that kind of indention which is supposed to happen but it is not happening. @Madebym above explained it excellently. I would turn the extension on and off and this issue seemed to only happen when the extension was on.

I haven't messed with this in a while so I will try to replicate the issue again and post back here. It seems to be working like it's supposed to so maybe something was fixed in a release, idk. If @Madebym is having the issue as of recent then maybe there is a sporadic thing going on here. I'll see what I can find.

Thanks
