### ISSUE TITLE
Can we have both standard and sublime3 modes at the same time?

### ISSUE THREAD

**Issue by sunabozu** [formulahendry/vscode-auto-close-tag#33]
Hi.

Is there a reason why those two modes are mutually exclusive? I like when tags close after `>`, but I also like when they close after entering `</`. The first option is for creating new markups, the second one is for editing existing code. Both may be handy at the same time.

**Comment by formulahendry** [comment]
Good point! Currently, I did not see any side effect of it. Will add an option to turn on both of the mode. In short term, you could use `Alt+.` (`Command+Alt+.` for Mac) to trigger close tag manually.

**Comment by formulahendry** [comment]
BTW, could you please let me know the detailed scenario of editing existing code? May be you could use [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)

**Comment by sunabozu** [comment]
That is a great extension, I use it too. Now when I thought about it, I noticed a bug in it (Auto Rename Tag). Basically, it doesn't work when the tag is multiline:
```html
<template>
  <li>
    <router-link
      class="pt-menu-item"
      :class="[ 'pt-icon-' + icon ]"
      style="max-height: 30px;"
      :to="to"
      >
      <span @click="onClick">{{ text }}</span>
    </router-link>
  </li>
</template>
```
Here it fails on the `router-link`.  That's how I ended up editing a closing tag manually.

**Comment by formulahendry** [comment]
Yes, thanks for your feedback! There is already an [issue](https://github.com/formulahendry/vscode-auto-rename-tag/issues/19) to track it.

**Comment by formulahendry** [comment]
Hi @sunabozu , a config entry `auto-close-tag.fullMode` is added (Default is `false`). Please install the latest version and set it as `true` so that both mode will be enabled.
