### ISSUE TITLE
TypeScript generics auto-close as if HTML

### ISSUE THREAD

**Issue by LukeTOBrien** [formulahendry/vscode-auto-close-tag#35]
Hello,

I have the auto-close extension.
I am currently working with RxJs and I found that when I use the type syntax for my generics: `Observable<Type>` the auto-close feature kicks in, so I get `Observable<Type></Type>`.

Perhaps the extension could read the file extension and check it against a whitelist of extensions so the .ts files no not auto-close, only .html?

Thanks

**Comment by formulahendry** [comment]
Yes, it is supported. Refer to #1
