### ISSUE TITLE
Using C# Generics like List<T> is Picked Up as a Tag by This Extension

### ISSUE THREAD

**Issue by DanJ210** [formulahendry/vscode-auto-close-tag#39]
When I'm coding in C# .cs files and I create something like `new List<T>` the extension things I'm trying to add a tag so it will add in closing tag like this `new List<T></T>` and sometimes I don't catch this when coding fast. This example is shown below.

![C# Tags](https://cloud.githubusercontent.com/assets/16159685/25865916/a1f9695c-34c2-11e7-9a25-81a34255cbeb.PNG)

**Comment by formulahendry** [comment]
Hi @DanJ210 , please see the #24 for the solution.

**Comment by DanJ210** [comment]
Oh. That's pretty nifty then! Thank you!
