### ISSUE TITLE
is there a way to suppress closing for some tags?

### ISSUE THREAD

**Issue by absurdist** [formulahendry/vscode-auto-close-tag#4]
hello,

can I suppress closing for some tags? (eg. meta)

**Comment by formulahendry** [comment]
How about providing a config that user could set the tag list that would not be auto closed? The default list would be HTML void elements: area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr, per [W3C spec](https://www.w3.org/TR/html-markup/syntax.html#syntax-elements)

**Comment by absurdist** [comment]
sounds perfect

**Comment by formulahendry** [comment]
Done. Please install the latest version and have a try.

**Comment by absurdist** [comment]
that was impressive
