### ISSUE TITLE
Auto close tag stopeed working on Version 1.12.2

### ISSUE THREAD

**Issue by shakeelosmani** [formulahendry/vscode-auto-close-tag#45]
Just to make sure my work space settings
  `{
    "editor.tabSize": 2,

    "workbench.editor.enablePreview": false,

    "auto-close-tag.enableAutoCloseTag": true,

    "auto-close-tag.SublimeText3Mode": false,

    "dart.sdkPath": "C:\\Program Files\\Dart\\dart-sdk\\bin",

    "auto-close-tag.excludedTags": [
        "cfset",
        "cfhttp",
        "cfqueryparam",
        "cfdump",
        "cfargument",
        "cfelse",
        "cfreturn",
        "br",
        "hr"
    ],

    "editor.insertSpaces": true,
    "python.linting.pylintEnabled": false,
    "files.trimTrailingWhitespace": true,
    "editor.formatOnPaste": true,
    "editor.minimap.enabled": true,
    "editor.snippetSuggestions": "top",
    "editor.detectIndentation": true,
    "editor.matchBrackets": true,
    "editor.autoClosingBrackets": true
  }`

![auto close bug](https://cloud.githubusercontent.com/assets/9120484/26210332/38554410-3bbd-11e7-980c-0383575a9273.PNG)
![vs version details](https://cloud.githubusercontent.com/assets/9120484/26210333/385618c2-3bbd-11e7-8997-769dd6bf999f.PNG)

**Comment by formulahendry** [comment]
@shakeelosmani , could you please use `Alt+.` to see whether the close tag will be added? Sometimes, the extension will not be immediately enabled right after the VS Code is opened.

**Comment by shakeelosmani** [comment]
Just checked it does not help

**Comment by formulahendry** [comment]
Could you disable all other extensions and try again?

**Comment by shakeelosmani** [comment]
Well this experiment finally lead to the reason for which your plugin does not work. The ColdFusion plugin I use once disabled your plugin starts working. But that's not a easy scenario for me, I cannot disable the ColdFusion plugin. There are two ColdFusion plugin that are in the market place and the same happens with the other plugin I just tested. What updates did you make to your plugin in the last change that it stopped working with the ColdFusion plugin?

You have to fix this :(

Thanks for your support.

**Comment by formulahendry** [comment]
There is no code logic change recently: https://github.com/formulahendry/vscode-auto-close-tag/blob/master/CHANGELOG.md    I think you need to report this issue to ColdFusion plugin.

**Comment by shakeelosmani** [comment]
well thank God I figured it out, it was due to this change in you plugin:
{
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "razor",
        "vue"
    ]
}

I had to add "*" for the time being. I tested against an HTML file and it worked , I realized this setting was causing it and then I just read about it.

**Comment by formulahendry** [comment]
Closing this issue then.
