### ISSUE TITLE
Doesn't work with HTML Liquid language extension

### ISSUE THREAD

**Issue by kevmon** [formulahendry/vscode-auto-close-tag#46]
Doesn't work with HTML Liquid language extension

**Comment by formulahendry** [comment]
Is this extension: https://marketplace.visualstudio.com/items?itemName=neilding.language-liquid ?

**Comment by formulahendry** [comment]
Hi @kevmon , Liquid has been supported now. Please install the latest version and have a try.

**Comment by kevmon** [comment]
Thanks!
