### ISSUE TITLE
Use backspace to undo auto close

### ISSUE THREAD

**Issue by jibbers42** [formulahendry/vscode-auto-close-tag#47]
I'm not sure if this is possible, but I think it would be useful.
(All examples below use a pipe to indicate cursor position)
```
// from here, hit '>' for auto close
<tag|
// from here, hit 'backspace' to undo auto close
<tag>|</tag>
// and end up with
<tag>|
```
This should only have effect if 'backspace' is the first character hit after auto close.

A great thing about auto close is you can go from here
```
<tag|
```
to here in only two keystrokes ('>' and 'enter')
```
<tag>
  |
</tag>
```

But it makes wrapping an existing section of html with a tag a bit more work. You can disable auto close and use sublime style closing which makes wrapping easier, but then takes several more keystrokes to achieve the final position above when not wrapping existing text. I think using backspace to undo the completion, but keep the '>' character would be pretty good solution for enabling both experiences.

**Comment by formulahendry** [comment]
Thanks for using this extension and your feedback! You could use `CTRL+Z` to undo auto close. So will not support `backspace` as it is not normal usage of `backspace`.
