### ISSUE TITLE
Closing a tag should check proper indentation

### ISSUE THREAD

**Issue by cvharris** [formulahendry/vscode-auto-close-tag#48]
![auto-close-and-indent](https://user-images.githubusercontent.com/4013888/26977119-56e87ef2-4cec-11e7-9d11-cf865437c591.gif)

This plugin detects very nicely that it needs to close a parent tag a few lines up, but it doesn't set the indentation correctly.

**Comment by formulahendry** [comment]
The indentation is not in the scope of Auto Clost Tag. You may want to open issue to https://github.com/microsoft/vscode/issues.
