### ISSUE TITLE
arrow function shouldn't trigger auto-close

### ISSUE THREAD

**Issue by ericvan76** [formulahendry/vscode-auto-close-tag#5]
every time when I type => inside a jsx element, it triggers auto-close, which is a bit annoying.

**Comment by formulahendry** [comment]
Hi @ericvan76 , could you please share the line of code snippet of the jsx?

**Comment by ericvan76** [comment]
<Icon name='xxx' onPress={()=></Icon>} />

</Icon> was auto added when I type =>, which is wrong.

**Comment by formulahendry** [comment]
Hi @ericvan76 , this issue has been fixed now, please try the latest version.

**Comment by ericvan76** [comment]
Fixed. thanks,
