### ISSUE TITLE
Self-closing tags are closed even if already closed

### ISSUE THREAD

**Issue by tandrieuxx** [formulahendry/vscode-auto-close-tag#51]
If I type `<`, then a `>` is automatically inserted. And if I add a `/`, nothing happens so I get `</>`: this is normal. But you usually name your tag before closing it.
So If I type `<something`, then I insert my `/`, a new `>` is added in addition of the one that was added after my `<`, resulting in `<something/>>`.

Basically, the plugin doesn't see the `>` already in place when trying to know if it should close a named self-closing tag.

**Comment by formulahendry** [comment]
For quick turnaround, you could disable closing self-closing tag automatically:
```
"auto-close-tag.enableAutoCloseSelfClosingTag": false
```

**Comment by tandrieuxx** [comment]
Yep I've done this, thank you !

**Comment by johnnytemp** [comment]
+1 Please fix it.
