### ISSUE TITLE
vscode-auto-close-tag is not activated for '*.md' file.

### ISSUE THREAD

**Issue by lonicerae** [formulahendry/vscode-auto-close-tag#53]
Hello,

It seems that the extension is not activated for '.md' file, which is a common suffix for Markdown file. But regarding the current supported language list:

```
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "blade",
        "ejs",
        "handlebars",
        "jinja",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "razor",
        "vue",
        "liquid"
    ],
```
the extension should be activated. Could you please let me know what extra configurations I should make?

Reproducing Steps:
==============
1. Open a blank `readme.md` file.
2. Try to type `<html>` and the extension is not activated.

Thank you!
Flos

**Comment by formulahendry** [comment]
Could you disable all other extensions and try again?

**Comment by lonicerae** [comment]
Hi,
I try disabling all the other extensions with 'always' option and leave only the auto-close-tag working, the same result. Thanks.

**Comment by lonicerae** [comment]
BTW, can you reproduce this? My vscode version is:

```
Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```

on a Linux platform.

**Comment by formulahendry** [comment]
I could not repro it.  How about typing `<html>` in other file (html, xml, plaintext)?

**Comment by lonicerae** [comment]
For html and plaintext, it's okay. Please review the screen recording about my test. Thanks!

[cannot-auto-complete.zip](https://github.com/formulahendry/vscode-auto-close-tag/files/1180659/cannot-auto-complete.zip)

**Comment by formulahendry** [comment]
This behavior is by design, as you are not typing `<abcd` then typing `>`.  You could use `"auto-close-tag.SublimeText3Mode": true` or use shortcut `Alt+.` (`Command+Alt+.` for Mac) to close tag manually.

**Comment by lonicerae** [comment]
Ah.. I see now. Thanks for your explaination!
