### ISSUE TITLE
How to add Classic ASP?

### ISSUE THREAD

**Issue by dotnetshadow** [formulahendry/vscode-auto-close-tag#55]
Hi I tried adding classic asp to the list as:
`
"
auto-close-tag.activationOnLanguage": [

        "html",  
        "xml",  
        "php",  
        "javascript",  
        "javascriptreact",  
        "typescript",  
        "typescriptreact",  
        "plaintext",  
        "markdown",   
        "razor",  
        "vue",  
        "asp"  
    ]`

But I'm guessing "asp" isn't what's needed here?

**UPDATE:** I actually got it working when I enabled:
`"auto-close-tag.fullMode":true,`

But it doesn't work when I use the following mode:
`"auto-close-tag.SublimeText3Mode": true`

**Comment by formulahendry** [comment]
No need to add `asp` to `auto-close-tag.activationOnLanguage`, it is already treated as `html` and enabled by default. If you set `"auto-close-tag.SublimeText3Mode": true`, it will only work on Sublime mode not VS mode. If you set `"auto-close-tag.fullMode":true`, both mode be will enabled.

**Comment by dotnetshadow** [comment]
Thanks for the explanation
I tried:
`"auto-close-tag.SublimeText3Mode": true`

But it wouldn't autocomplete like sublime text does on an **asp** page, yet when I tried **html** file extension type page it did work

**Comment by formulahendry** [comment]
Are the content totally the same? Could you share the screenshot?

**Comment by dotnetshadow** [comment]
UPDATE: I found the issue to be another extension Classic ASP Language Support seems to interfere with it
