### ISSUE TITLE
Multi cursor support

### ISSUE THREAD

**Issue by Morgy93** [formulahendry/vscode-auto-close-tag#56]
Hello,

is it possible to offer multi cursor support?
While having multiple cursors, only the first tag gets auto closed.

**Comment by formulahendry** [comment]
Duplicated with #16

**Comment by Morgy93** [comment]
Well, I learned something new about GitHub issue search then.
![image](https://user-images.githubusercontent.com/7961978/29619720-1379c1ec-881c-11e7-9118-b7b8f6f961b4.png)
Seems to be no wildcard~
Which is funny because multiple works fine for both:
![image](https://user-images.githubusercontent.com/7961978/29619781-3d7cc962-881c-11e7-88e4-8915da0b480d.png)

Anyway, thanks for info!
