### ISSUE TITLE
In TypeScript, type declarations are erroneously autocompleted 

### ISSUE THREAD

**Issue by dale-dixon** [formulahendry/vscode-auto-close-tag#58]
In TypeScript type declarations are erroneously auto-completed. 

![image](https://user-images.githubusercontent.com/20524988/29996785-2845b89c-8fd3-11e7-89a4-97da3df4bf60.png)

limit action to inside of string delimiters:  '...' , "...", `...`

This may also be a problem with other languages.

![image](https://user-images.githubusercontent.com/20524988/29997900-312c032a-8fed-11e7-8d7d-42779d9fd16e.png)

**Comment by formulahendry** [comment]
Duplicated with #17
