### ISSUE TITLE
Automatically adds close tags to TypeScript files

### ISSUE THREAD

**Issue by lostllama** [formulahendry/vscode-auto-close-tag#6]
If I try to make a generic interface:

`export interface ITest<Hello>`

The moment I finish typing `<Hello>`, it adds `</Hello>` in a .ts file.

**Comment by formulahendry** [comment]
You could set the languages that the extension will be activated:
```json
{
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "javascript"
    ]
}
```
Refer to https://github.com/formulahendry/vscode-auto-close-tag#configuration

**Comment by lostllama** [comment]
Yeah, I saw that afterwards. Is there any chance you could add this to the description you see in VS Code so that other users don't make the same mistake as I did? :)

**Comment by formulahendry** [comment]
It has already shown in the extension page: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag 😃

**Comment by michaeljota** [comment]
Hi! I wonder if maybe you can make this extension to work only in HTML server files?

**Comment by formulahendry** [comment]
@michaeljota , which server files you want to make it work?
