### ISSUE TITLE
auto close like sublime by typing </

### ISSUE THREAD

**Issue by lwcutter** [formulahendry/vscode-auto-close-tag#60]
this is currently not possible despite documentation stating it is. i have installed the extension, but this setting

"auto-close-tag.SublimeText3Mode": false

which needs to be set to true is NOT located in the settings. And this is VERY aggravating.

**Comment by formulahendry** [comment]
You need to add that setting yourself. Please read the doc for creating User Settings: https://code.visualstudio.com/docs/getstarted/settings#_creating-user-and-workspace-settings
