### ISSUE TITLE
Space before closing bracket prevents auto close

### ISSUE THREAD

**Issue by dpremo-turner** [formulahendry/vscode-auto-close-tag#63]
I like to keep spaces in my elements for readability and in case I want to add attributes later.  So when I create a div, I tend to type something like this:

`<div class='asdf' >`

This extension doesn't recognize this as a tag that should be auto closed.  I've tested setting `auto-close-tag.fullMode` and `auto-close-tag.SublimeText3Mode` but neither likes a space before the closing bracket.  

Am I violating some code standard or does the extension just not accommodate my coding style?

**Comment by formulahendry** [comment]
Hi @dpremo-turner , this has been fixed, please try the latest version.
