### ISSUE TITLE
Adding html as activation language?

### ISSUE THREAD

**Issue by alexchantastic** [formulahendry/vscode-auto-close-tag#64]
Is it possible to add `html` as an activation language? I prefer how Sublime handles closing tags so I use `"auto-close-tag.SublimeText3Mode": true`, but I'd like this behavior to carry over to HTML files as well so I disabled VSCode's default auto close tag behavior (`"html.autoClosingTags": false`) and added `html` to the activation language list, but this doesn't seem to be working.

```
"auto-close-tag.activationOnLanguage": [
    "html",
    "xml",
    "php",
    "blade",
    "ejs",
    "jinja",
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "plaintext",
    "markdown",
    "vue",
    "liquid",
    "twig"
]
```

**Comment by formulahendry** [comment]
Hi @alexchantastic , is the SublimeText3Mode working for other files? Have you tried other languages files?

**Comment by alexchantastic** [comment]
@formulahendry yes, `auto-close-tag.SublimeText3Mode` seems to work with the other language files that I specified in `auto-close-tag.activationOnLanguage` (tested Twig and Markdown).

**Comment by formulahendry** [comment]
How about `xml`? And what html code do you try?

**Comment by alexchantastic** [comment]
Something strange might be happening... I just created a new HTML file and it works fine, but it does not work on any file I have opened before. Is there some cache I have to clear? I have quit/restarted VSCode and run Reload Window.

I just just tested with a new XML file and it works fine.

I have been testing with a simple `<div>` tag.

**Comment by formulahendry** [comment]
No cache. Actually, even restarting VS Code is not needed. Closing this issue then. You could reopen if you meet with the issue again.

**Comment by alexchantastic** [comment]
Once I figure out how to get the files I've opened to work I'll post the fix here.

Thanks for your help debugging 😃 .
