### ISSUE TITLE
How to use auto close without language ID - non supported language

### ISSUE THREAD

**Issue by jp41011** [formulahendry/vscode-auto-close-tag#67]
I'm trying to get this to work with my **CFML** files that have the **".cfm"** extension.
But I don't know how to go about finding the language ID so that I can add it to the **"auto-close-tag.activationOnLanguage"** array.
Markup tags in cfml are mostly the same markups that you see in html.

**Comment by jp41011** [comment]
I figured it out.
I was able to get the language identifier by bring up the "Select Language Mode" and when you highlight the language you want the language identifier will be in between the parenthesis that is to the right of the language name.

Ex: In the language select list I see
CFML (**lang-cfml**)
in this case the language id was "**lang-cfml**".
I added this id to the **auto-close-tag.activationOnLanguage**  and now it works with **CFML** files.

**Comment by formulahendry** [comment]
Good to know that. Closing this issue then
