### ISSUE TITLE
Img tag doesn't close automatically

### ISSUE THREAD

**Issue by KevinBollengier** [formulahendry/vscode-auto-close-tag#68]
My image tag doesn't close automatically when pressing tab, not sure wether this is a bug or a setting somewhere?

**Comment by formulahendry** [comment]
Hi @KevinBollengier , `img` tag is void element: http://w3c.github.io/html-reference/syntax.html#void-element, it should not have a end tag.

**Comment by KevinBollengier** [comment]
Let me clarify what I mean with closing: even a void tag has a "closing" part which basically is "/>", but the plugin doesn't autocomplete this for me?

**Comment by formulahendry** [comment]
Please check the doc for all the feature the extension provides: https://github.com/formulahendry/vscode-auto-close-tag#usages
Using `tab` to trigger is not a feature of this extension. I think you are talking about Emmet. This is implemented by VS Code it self: https://code.visualstudio.com/docs/editor/emmet#_using-tab-for-emmet-expansions
