### ISSUE TITLE
Not working after update to vscode 1.18.1

### ISSUE THREAD

**Issue by name-k** [formulahendry/vscode-auto-close-tag#71]
After an update to **1.18.1** the extension started to cause weird bugs. Any attempt to close the tag with a hotkey causes different sort of vscode lags, for example several other extensions stop to work (eslint, prettier, git-lens and some more), along with that vscode start to load CPU to 100% and freeze from time to time. 
SublimeText mode works fine though. 

Problems described above also present with **vscode-auto-close-tag** as the only enabled extension. 
Rollback to **1.18.0 fixed the issue**. 

Did not notice anything suspicious in the dev console.

**Comment by formulahendry** [comment]
Hi @name-k , I could not repro this using 1.18.1. Could you disable all other extensions and try again?

**Comment by formulahendry** [comment]
Oh, seems you have already disable other extensions. Could you share the code snippet to repro this? Or just a simple `<div></div>` could repro?

**Comment by name-k** [comment]
Yes, happens even with simple `<div></div>` for me. Also I tried clean install and had the same issue.

**Comment by formulahendry** [comment]
What file you are editing?

**Comment by name-k** [comment]
I'm editing a React.js component, language mode is `javascriptreact`

**Comment by formulahendry** [comment]
How about try other file type? e.g. PHP

**Comment by name-k** [comment]
Did not have a chance to check with PHP and etc. Now when I updated vscode to 1.19.1 - it works fine.
