### ISSUE TITLE
SublimeText3Mode: true + enableAutoCloseTag: false not working as expected

### ISSUE THREAD

**Issue by peps** [formulahendry/vscode-auto-close-tag#72]
Hi there, i'm trying to set it up so that HTML tags only close using SublimeText3Mode. 

In my user settings...

I tried this:

"auto-close-tag.SublimeText3Mode": true,

I tried this:

"auto-close-tag.SublimeText3Mode": true,
"auto-close-tag.enableAutoCloseTag": false,

I tried this:

"auto-close-tag.SublimeText3Mode": true,
"html.autoClosingTags": false,

I tried this:

"auto-close-tag.SublimeText3Mode": true,
"auto-close-tag.enableAutoCloseTag": false,
"auto-close-tag.enableAutoCloseSelfClosingTag": false,

It either disables closing tags completely, or it does it all Sublime closing and tag auto closing. How do I get it to just do SublimeText3Mode? Am I missing something, or is this bugged?

Thanks!

**Comment by formulahendry** [comment]
Are you working on HTML file? Then you need three settings (you need to add `html` into `auto-close-tag.activationOnLanguage`):
```json
"auto-close-tag.SublimeText3Mode": true,
"html.autoClosingTags": false,
"auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "blade",
        "ejs",
        "jinja",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "vue",
        "liquid",
        "erb",
        "lang-cfml",
        "cfml"
    ]
```

**Comment by peps** [comment]
That works, thanks! I'm new to VSCode, seems like a pain in the ass to have to specify activeationOnLanguage... it should automatically be active on any file type that uses a tag syntax.

Anyways, thanks for the great support!

**Comment by formulahendry** [comment]
BTW, you could use `["*"]` to enable it on any language:
```json
"auto-close-tag.activationOnLanguage": ["*"]
```

**Comment by mikesale** [comment]
Is this no longer working? I seem to be unable to enable SublimeText3Mode only in the current version. 
  "html.autoClosingTags": false,
  "auto-close-tag.activationOnLanguage": ["*"],
  "auto-close-tag.enableAutoCloseSelfClosingTag": false,
  "auto-close-tag.enableAutoCloseTag": false,
  "auto-close-tag.SublimeText3Mode": true
