### ISSUE TITLE
jsx auto close self closing tag bug

### ISSUE THREAD

**Issue by leonbec** [formulahendry/vscode-auto-close-tag#76]
In jsx
![jsx-bug](https://user-images.githubusercontent.com/28700378/36439740-a861dcdc-16d2-11e8-90c3-6c576129c83b.gif)
It's normal in html
![html](https://user-images.githubusercontent.com/28700378/36439764-b65fe7d4-16d2-11e8-9b27-2a81fa01af66.gif)

**Comment by formulahendry** [comment]
Duplicated with #51 

For quick turnaround, you could disable closing self-closing tag automatically:
```
"auto-close-tag.enableAutoCloseSelfClosingTag": false
```
