### ISSUE TITLE
support auto-closing after slash

### ISSUE THREAD

**Issue by anvish** [formulahendry/vscode-auto-close-tag#8]
Please, provide an option to insert closing tag only after `</` was entered.

**Comment by formulahendry** [comment]
@anvish , thanks for your feedback, will have plan to implement that.

**Comment by formulahendry** [comment]
@anvish , I have implemented this feature. Please install the latest version and follow the [setting](https://github.com/formulahendry/vscode-auto-close-tag#sublime-text-3-mode) to have a try!
