### ISSUE TITLE
ALT + . and F1 Close Tag not working

### ISSUE THREAD

**Issue by ishraqiyun77** [formulahendry/vscode-auto-close-tag#80]
Working on a React project with JavaScript React as the file format in VSCode 1.21.1.

Type `<div>` and it will automatically complete the tag usually (sometimes it doesn't, but honestly I have been meaning to turn that off anyway).

I prefer manually completing tags using `ALT + .` This doesn't do anything however. If I do `F1 > Close Tag` still nothing. So basically I am typing `<div>` go to press `ALT + .` or `F1 > Close Tag` and nothing happens.

On Windows, so `ALT + .` should be the command.

Let me know what other information I can provide.

**Comment by formulahendry** [comment]
If you trigger `ALT + .` after `<div>`, does it work? What's your code not working?

**Comment by ishraqiyun77** [comment]
Correct, type in `<div>` and press `ALT + .` and it should close it, but it does not. That is basically my code at this point as I am testing out the functionality of the extension.

**Comment by ishraqiyun77** [comment]
Disregard. I started on a new React component and it appears to work. Most be something related to the component I was working on.

**Comment by ishraqiyun77** [comment]
OK, sorry. Got to a spot in this new component that it is happening again.

If I have something like this:

```
render() {
    return (
        <div>
    )
}
```
It will autocomplete the tag with `</div>` and it will also let me use `ALT + .`.

However, it doesn't work if there are other tags between it like this:
```
render() {
    return (
        <div>
            <Button onClick={this.toggle}>Test</Button>
            <Modal isOpen={modal} toggle={this.toggle}>
                <ModalHeader>Test Header</ModalHeader>
                <ModalBody>Test Body</ModalBody>
            </Modal>
    )
}
```
And I go to add the closing `</div>` after the `</Modal>` with `ALT + .` then it does not work. I used to do this in Sublime Text 3 so it has become habit, so that is why I am doing it that way.

**Comment by formulahendry** [comment]
Could not repro from my side.. Could you please disable all other extension and try again?
![auto-close](https://user-images.githubusercontent.com/1050213/39092322-f31cd57a-463d-11e8-98be-cc7050ebc6ad.gif)

**Comment by feens** [comment]
I'm actually having the same issue.  VSCode v1.27.2.  Here's sample code that has issues:

```
  renderResourceListItem(item: any): JSX.Element {
    return (
      <ResourceList.Item
        id={item.id}
        onClick={partial(this.props.goToUrl, item.url)}
        persistActions
        shortcutActions={[{
          content: I18n.t('BusinessList.editButton'),
          onAction: partial(this.props.goToUrl, `${baseRoute}/businesses/${item.id}/edit`),
        }]}
      >
        <Stack distribution="equalSpacing">
          <TextStyle variation="strong">
            <div>{item.name}</div>
          </TextStyle>
        </Stack>
      </ResourceList.Item>
    );
  }
```

**Comment by feens** [comment]
I even tried just doing a simple `<div>` on the line after the return statement and it wouldn't work.  Seems to not work in most of my *tsx* files

**Comment by mesa123123** [comment]
I'm getting the same issue here;
Working on a Vue project file, whenever I push "alt+." but it seems to be a performance issue on my side rather than anything else; have you tried waiting on the tag to close?

**Comment by townofdon** [comment]
Having the same issue.

```
VSCode v. 1.30.2
auto-close-tag v. 0.5.6
```

I've been able to replicate this issue in PHP and React projects. Default is just to switch over to Sublime when this stops working, which I hate doing.

Seems to stop working after initial tag autocompletion (`<div>|</div>` where `|` is the cursor), and then I delete the `</div>`. Now I can no longer add closing tag manually by pressing `CMD + ALT + .` (Mac)
