### ISSUE TITLE
Feature request: Auto close brace when in HTML element (in JavaScript).

### ISSUE THREAD

**Issue by 76784** [formulahendry/vscode-auto-close-tag#81]
Very nice extension. I have a feature request, which you might be able to implement with your expertise.

The default behavior of VSCode is - **when working in JavaScript** - to auto close brackets and braces. For example:

```JavaScript
const foo = [
	{}
]
```

VSCode auto closes "]" and "}" in the above.

However, when working in React.js, one often needs to use braces while working in HTML (which is within JavaScript). For example:

```html
class App extends Component {
  render() {
    return (
      <div className="App">
          return (
            <span>{}</span>
          )
      </div>
    );
  }
}
```

In the span element above, VSCode does not auto close the closing "}". Similarly, VSCode does not auto close braces in a *.html file:

```html
<div>{}</div>
```

In the div element above, VSCode does not auto close the closing "}". 

With the popularity of React, this would be a nice feature to have. Thanks for considering it.

**Comment by formulahendry** [comment]
Thanks @76784 for your feedback.
However it would make more sense to have this feature in a separate extension, since this repo is for `auto-close-tag` not brace
