### ISSUE TITLE
Extension activated on startup

### ISSUE THREAD

**Issue by prashantkhurana** [formulahendry/vscode-auto-close-tag#84]
I was doing some manual profiling of my extensions and one of the suggested items is to look at the "show running extensions" view. I opened vscode with no folder and I see that auto-close-tag was activated on startup. 

![image](https://user-images.githubusercontent.com/6133816/39387847-02db7d8a-4a4a-11e8-8e19-f71579176b7b.png)

My settings for the extensions are pretty barebones, so I was not expecting that. 

![image](https://user-images.githubusercontent.com/6133816/39387863-1bcdd720-4a4a-11e8-86c4-346039a7e4dc.png)

**Comment by formulahendry** [comment]
Hi @prashantkhurana , this is expected behavior since the extension would always be activated and only take effect per setting of `activationOnLanguage`. Currently, there is no way for end user to customize the real activationOnLanguage
