### ISSUE TITLE
Auto-closing the closing tag when it is empty

### ISSUE THREAD

**Issue by nikonorovsv** [formulahendry/vscode-auto-close-tag#88]
Hi! It's very convenient in Jetbrains editors, when I have full tag `<v-icon>icon_name</v-icon>` and if I want to replace it to empty tag `<v-icon v-text="icon_name" />` I just put `/` into opening tag and closing tag is automatically deleted. In vscode, I get the following `<v-icon />></v-icon>` Is it possible to get a similar behavior in this extension?

**Comment by alexmccabe** [comment]
Duplicate of #83
