### ISSUE TITLE
Close tag using a shortcut

### ISSUE THREAD

**Issue by emadb** [formulahendry/vscode-auto-close-tag#9]
It would be useful having an option to set a shortcut to close the tag. Sometimes the autoclose is too intrusive and a shortcut would be better.
Sublimetext have the Cmd+alt+. 
Thanks anyway for your plugin!

**Comment by formulahendry** [comment]
@emadb , thanks for your feedback! I have added a config entry `auto-close-tag.enableAutoCloseTag` to turn on/off auto close tag, and shortcut `Ctrl+Alt+.` to close tag manually. Please install the latest version and follow the instruction to have a try. 😄

**Comment by emadb** [comment]
Thankyou! :-)
