### ISSUE TITLE
Enhancement: Rename close-tag along with open tag

### ISSUE THREAD

**Issue by junalmeida** [formulahendry/vscode-auto-close-tag#93]
Just like VS IDE, while renaming the open tag or close tag, rename the other as well.

![tags](https://user-images.githubusercontent.com/991675/41917577-1ff2e97e-7931-11e8-995e-e7f11cce9cc6.gif)

**Comment by formulahendry** [comment]
I think what you need is https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
